import {formatNumber,formatYoy,yoy,toNumber} from "./metrics";
export const pageStyle={minHeight:"100vh",background:"#f5f7fb",padding:24,fontFamily:"Arial, sans-serif",color:"#0f172a"};
export const cardStyle={background:"#fff",border:"1px solid #e5e7eb",borderRadius:18,padding:20,boxShadow:"0 8px 24px rgba(15,23,42,.06)"};
export const inputStyle={width:"100%",padding:10,borderRadius:10,border:"1px solid #cbd5e1",fontWeight:700,boxSizing:"border-box"};
export function Nav(){return <div style={{display:"flex",gap:10,flexWrap:"wrap",marginBottom:20}}><a href="/" style={{background:"#0f172a",color:"#fff",borderRadius:12,padding:"10px 14px",textDecoration:"none",fontWeight:900}}>Hub</a>{[["Weekly","/theograce/weekly-reporting"],["Monthly","/theograce/monthly-reporting"],["History","/theograce/history"]].map(([l,h])=><a key={h} href={h} style={{background:"#ede9fe",color:"#6d28d9",borderRadius:12,padding:"10px 14px",textDecoration:"none",fontWeight:900}}>{l}</a>)}</div>}
function status(metric,v){v=toNumber(v); if(metric==="csat") return v>=4.2?["On goal","#166534","#dcfce7"]:v>=4?["Above minimum","#854d0e","#fef9c3"]:["Below minimum","#991b1b","#fee2e2"]; if(metric==="sla") return v<=10?["Goal","#166534","#dcfce7"]:v<=20?["Agent target","#854d0e","#fef9c3"]:["Above target","#991b1b","#fee2e2"]; return ["Info","#1d4ed8","#dbeafe"]; }
export function Badge({metric,value}){const s=status(metric,value); return <span style={{background:s[2],color:s[1],padding:"5px 9px",borderRadius:999,fontSize:12,fontWeight:900}}>{s[0]}</span>;}
export function SummaryCard({label,value,hint,color}){return <div style={{...cardStyle,borderTop:`6px solid ${color}`}}><div style={{color:"#64748b",fontWeight:800,fontSize:13}}>{label}</div><div style={{fontSize:34,fontWeight:950,marginTop:8}}>{value}</div><div style={{marginTop:8,color:"#64748b",fontWeight:700}}>{hint}</div></div>;}
export function MetricTable({title,metric,unit,goal,data,onChange=()=>{},editable=true}){const rows=[["TGR US","us2026","us2025"],["TGR UK","uk2026","uk2025"]]; return <div style={cardStyle}><h2 style={{margin:0,fontSize:24}}>{title}</h2><div style={{marginTop:6,color:"#64748b",fontWeight:700}}>{goal}</div><div style={{overflowX:"auto",marginTop:18}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr style={{textAlign:"left",color:"#64748b",borderBottom:"1px solid #e5e7eb"}}><th style={{padding:10}}>Brand</th><th style={{padding:10}}>2026</th><th style={{padding:10}}>2025</th><th style={{padding:10}}>YOY</th><th style={{padding:10}}>Status</th></tr></thead><tbody>{rows.map(([label,cur,prev])=>{const c=toNumber(data?.[cur]),p=toNumber(data?.[prev]),y=yoy(c,p); return <tr key={label} style={{borderBottom:"1px solid #f1f5f9"}}><td style={{padding:10,fontWeight:900}}>{label}</td><td style={{padding:10}}>{editable?<input type="number" step="0.01" value={data?.[cur]??""} onChange={e=>onChange(cur,e.target.value)} style={inputStyle}/>:<b>{unit==="hours"?`${formatNumber(c,1)}h`:formatNumber(c,metric==="conversations"?0:2)}</b>}</td><td style={{padding:10}}>{editable?<input type="number" step="0.01" value={data?.[prev]??""} onChange={e=>onChange(prev,e.target.value)} style={inputStyle}/>:<b>{unit==="hours"?`${formatNumber(p,1)}h`:formatNumber(p,metric==="conversations"?0:2)}</b>}</td><td style={{padding:10,fontWeight:900,color:y>=0?"#15803d":"#b91c1c"}}>{formatYoy(y)}</td><td style={{padding:10}}>{metric!=="conversations"?<Badge metric={metric} value={c}/>:"—"}</td></tr>})}</tbody></table></div><div style={{marginTop:12,color:"#64748b",fontSize:13}}>Source: Kustomer · Weekly 7 days view {unit?`· Unit: ${unit}`:""}</div></div>}
